### ISSUE TITLE
Discussion: string style

### ISSUE THREAD

**Issue by amiel** [ActionSprout/coding-styles#3]
There's one more decision to make in the ruby style guide.

This section has two options, and the style guide recommends picking one: https://github.com/ActionSprout/coding-styles/blob/master/ruby.md#consistent-string-literals

I would be happy either way. I'd even be ok with removing this section of the style guide, as I don't think we are very consistent right now anyway.

This debate has been going for quite a while. Usually the arguments are like this:

* For single quotes:

   There's a slight performance improvement, since ruby doesn't have to scan the string for possible interpolations.

* For double quotes:

   It's likely that you will end up interpolating some strings and it's annoying to change them. The performance improvement is negligible.

To be honest, I'm not very consistent about this. Sometimes I feel like following the spirit of both rules and using single quotes for things that really are not likely to be interpolated, like strings that are identifiers (which would be a good case for using a ruby symbol, but sometimes that just doesn't end up being the case), and then double quotes for strings of text like copy or whatever, which seem to have a higher likely-hood of being interpolated in the future. However, these guidelines are too subjective to be in a style-guide. Hence the idea of just removing this section and not worrying about it.

Other notes: Our javascript (es6) style-guide requires using single quotes.

Thoughts?

**Comment by andreafrost** [comment]
I don't have a strong opinion one way or anther, but after reading several articles:
 - http://www.rubyletter.com/blog/2017/01/13/single-quotes-vs-double-quotes.html
 - http://anti-pattern.com/always-use-double-quoted-strings-in-ruby
 - https://www.viget.com/articles/just-use-double-quoted-ruby-strings

I feel inclined to lean towards double quotes as the standard.

> Since there is no measurable performance advantage for either, any time (however marginal) spent thinking or talking about a choice between the two is wasted. When you prefer single quoted strings, you have to think when you need interpolation. When you use double quoted strings, you never have to think. (I'd also add, anecdotally, that apostrophes are more prevalent in strings than double quotes, which again means less thinking when using double-quoted strings.)

> Therefore always using double-quoted strings results in the least possible wasted time and effort.

**Comment by amiel** [comment]
@andreafrost I agree.

**Comment by kyle-rader** [comment]
Hmmm, so in Node you have 3 string options.  
```node
> console.log('I\'m a "string"')
"I'm a string"
> console.log("I'm a \"string\"")
"I'm a string"
> console.log(`I'm a "string" ${moreStuff}`)
"I'm a string that stuff"
```
So the standard on single quotes is like, meh in my opinion.  Using 
```
`Back Ticks`
```
Gives you the most flexibility and best chance at not needing to change things.

Since `" "` is our interpolated string in Ruby I would also lean towards standardizing on the `"` providing the most stability and least need for change.

**Comment by kyle-rader** [comment]
@amiel Actually this discussion makes me want to switch our JS standard to double quotes also.  Chrome's default is double quoted strings.  Valid JSON is only double quotes strings.

**Comment by amiel** [comment]
Ok, I'll PR using double quotes by default.

@kyle-rader I'd be ok with switching our JS standard to use double quotes, although we already have a strong [style-guide recommendation to use single quotes or backticks](https://github.com/ActionSprout/coding-styles/blob/master/es6.md#strings) and most of our existing code uses single quotes. I'm fine either way...

**Comment by amiel** [comment]
OMG I have one new argument to consider. I have realized that I have a strong habit of using single quotes. This is partially since single quotes don't require using the shift key. They are just easier to type...

Anyway, I'm still fine either way. I just thought I'd throw that in to the mix in case it sways anyone else 😝

**Comment by nathancarnes** [comment]
@amiel I'm pretty sure your laptop has with not one, but _two_ shift keys. 

Anyway, I think that it's worth using double quotes to produce cleaner diffs when adding/removing interpolation.
